# Generated by Django 4.1.3 on 2024-02-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=100)),
                ('customerName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='invoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(null=True)),
                ('unitPrice', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceApp.invoice')),
            ],
            options={
                'db_table': 'invoiceDetail',
            },
        ),
    ]
